#+TITLE: jlastfm widget
#+AUTHOR: Justin Hornosty (jjrh)
#+EMAIL: jjrh70@gmail.com
#+OPTIONS: section-number-format: 1
#+options: num:nil
#+OPTIONS: ^:nil
#+preamble: ji
#+STARTUP: align showall

* Intro
  After taking a look at http://imagegen.last.fm/basic10/tracks/slicenice.gif a coworker had on his website, I said:  "oh I can do better...". 

  Since [[http://getbootstrap.com/][bootstrap]] is my new go-to thing for web-design (/since they do a better job than I ever could/) I designed the base widget
  template to use bootstrap components. This could be easily re-factored out.

* Goals
   - Drop in solution - input my username and bam we got stats. This lead to the next point,
   - No API key usage. All the data is we need is available without needing a api key. The only advantage one would get is json returned data.
   - Bootstrap usage to have an aesthetically pleasing look that would fit the rest of my site and allow the widget to be themed
     
  One of the goals of the project was to not use api keys to access data. All the data I needed/wanted was offered in XML
  and or json format. (sadly not much in json) This fit the goal of having a mostly drop in 

* Reference & sources:
    
  | name      | repo                                                 | file/s                                                                        |
  |-----------+------------------------------------------------------+-------------------------------------------------------------------------------|
  | jQuery    | https://github.com/jquery/jquery  (not sure version) | unsure                                                                        |
  | bootstrap | https://github.com/twbs/bootstrap (version 3?)       | https://github.com/twbs/bootstrap/tree/master/dist                            |
  | xml2json  | https://github.com/josefvanniekerk/jQuery-xml2json   | https://github.com/josefvanniekerk/jQuery-xml2json/blob/master/js/xml2json.js |
  |           |                                                      |                                                                               |

  And of course [[http://www.last.fm/][last.fm]]!

-----------------------------------------------  
  
